import Head from 'next/head'

import Map from '../components/Map/index'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <main className={styles.container}>
      <Head>
        <title>X-Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Map />
    </main>
  )
}
